package com.ahuja.sons.newapimodel

data class AddTicketRequestModel(
    val AlternatePhone: String = "",
    val AssignTo: String = "",
    val BranchId: String = "",
    val CardCode: String = "",
    val CaseOrigin: String = "",
    val ContactAddress: String = "",
    val ContactEmail: String = "",
    val ContactName: String = "",
    val ContactPhone: String = "",
    val ContractType: String = "",
    val CountryCode: String = "",
    val CountryCode1: String = "",
    val CreatedBy: String = "",
    val DeliveryID: String = "",
    val Description: String = "",
    val DueDate: String = "",
    val Observation: String = "",
    val Priority: String = "",
    val Status: String = "",
    val SubType: String = "",
    val TicketEndDate: String = "",
    val TicketItems: ArrayList<TicketItem> = ArrayList(),
    val TicketStartDate: String = "",
    val TandC: String = "",
    val TicketStatus: String = "",
    val Title: String = "",
    val Type: String = "",
    val Zone: String = "",
    val ZonalManagerRemark: String = "",
    val id: Int = 0
)