package com.ahuja.sons.newapimodel

data class DocumentLineXX(
    val At_Capacity: String,
    val CostingCode2: String,
    val Ct_Capacity: String,
    val DiscountPercent: Int,
    val FreeText: String,
    val Ht_Capacity: String,
    val IT_Intall: String,
    val IT_LOCharges: String,
    val IT_MICharges: String,
    val ItemCode: String,
    val ItemDescription: String,
    val LineNum: Int,
    val Machine_Body_Material: String,
    val Machine_Colour: String,
    val Machine_Dimension: String,
    val OrderID: String,
    val Pro_Capacity: String,
    val ProjectCode: String,
    val Quantity: Int,
    val Sales_Type: String,
    val Special_Remark: String,
    val Tap_Qty: String,
    val Tap_Type: String,
    val Tax: Int,
    val TaxCode: String,
    val Type_of_Machine: String,
    val UV_Germ: String,
    val U_FGITEM: String,
    val UnitPrice: Double,
    val UomNo: String,
    val customize: String,
    val id: Int
)