package com.ahuja.sons.jsonmodel

data class ModelObjectForTicketDetails(
    var LogisticPerson: String = "N/A",
    var Remarks: String = "N/A",
    var ShippedDate: String = "N/A",
    var ExpDeliveryDate: String = "N/A",
    var ContactNo: Int = 0,
    var ShipmentCsgNo: String = "N/A",
    var ConsignmentDocumentsAttached: String = "N/A",

    var datastatus: String = "N/A",
    var dataremark: String = "N/A",
    var DesignEngineerName: String = "N/A",
    var FinalSurveyReportattached: String = "N/A",
    var status: String = "N/A",
    var shaft: String = "N/A",
    var From: String = "N/A",
    var TypeofElevator: String = "N/A",
    var Other: String = "N/A",
    var ShaftAvailability: String = "N/A",
    var ShaftWidth: String = "N/A",
    var ShaftDepth: String = "N/A",
    var Travel: String = "N/A",
    var OverHead: String = "N/A",
    var Pit: String = "N/A",
    var WidthA: String = "N/A",
    var WidthC: String = "N/A",
    var StructureOpening: String = "N/A",
    var FinalDrawingAttached: String = "N/A",
    var DeviationsObserved: String = "N/A",
    var DeviationsDetails: String = "N/A",
    var FinalDrawingApproval: String = "N/A",
    var SalespersonName: String = "N/A",
    var PurchaeRequestNo: String = "N/A",
    var PurchaeRequestDate: String = "N/A",
    var PurchaeRequestTo: String = "N/A",
    var PurchaeRequestType: String = "N/A",
    var DocumentDate: String = "N/A",
    var ClientApprovalFOS: String = "N/A",
    var FinalApprovedDrawingAttached: String = "N/A",
    var CustomerPOAttached: String = "N/A",
    var FinalSupplierofferAttached: String = "N/A",
    var ProjectNumber: String = "N/A",
    var RequestedName: String = "N/A",
    var BranchName: String = "N/A",
    var SiteEngineerName: String = "N/A",
    var CivilWorkStatus: String = "N/A",
    var CivilWorkDetails: String = "N/A",
    var ScaffoldingRequired: String = "N/A",
    var ScaffoldingBy: String = "N/A",
    var ScaffoldingType: String = "N/A",
    var ScaffoldingInspectionReportAttached: String = "N/A",
    var ScaffoldingStatus: String = "N/A",

    var LogisticPersonName: String = "N/A",
    var ClientName: String = "N/A",
    var RecepientName: String = "N/A",
    var RecepientPhoneNo: String = "N/A",

    var RecepientEmirateID: String = "N/A",
    var DeliveryStatus: String = "N/A",
    var ProofofDeliveryAttached: String = "N/A",
    var PaymentStatus: String = "N/A",
    var PendingAmount: Int = 0,
    var InvoiceID: String = "N/A",
    var InvoiceDate: String = "N/A",
    var DiscrepenciesFound: String = "N/A",
    var CorrectiveActionRequired: String = "N/A",
    var QualityCheckReportAttached: String = "N/A",
    var QualityRating: String = "N/A",
    var CompletionReport: String = "N/A",
    var PowerSupplyAvailability: String = "N/A",
    var PaymentConfirmation: String = "N/A",
    var Invoice: String = "N/A",
    var SupplyAvailabilityDate: String = "N/A",
    var QualityPersonName: String = "N/A",

    var CreatedRequest: String = "N/A",
    var SupervisorName: String = "N/A",
    var thirdrdPartyOrgName: String = "N/A",
    var CertificationDate: String = "N/A",
    var ValidTill: String = "N/A",
    var LineManagerName: String = "N/A",
    var ThirdPartyInspectionReportAttached: String = "N/A",
    var MNo: String = "N/A",
    var ApprovedQualityInspectiontwoAttached: String = "N/A",

    var TrainingStatus: String = "N/A",
    var MaintenanceInspectionReportAttached: String = "N/A",
    var Documentsattached: String = "N/A",
    var ProjectNo: String = "N/A",

    var MaintenanceTransmittalDocument: String = "N/A",
    var PPSchedulePreparation: String = "N/A",

    //Addtional Tickets details
    var CorrectIssueType: String = "N/A",
    var ScheduledVisitDate: String = "N/A",
    var CorrectiveActions: String = "N/A",
    var RepairRequestNeeded: String = "N/A",
    var MaterialUsed: String = "N/A",

    var SysSchdeduleDate: String = "N/A",
    var TechnicalRequest: String = "N/A",
    var RepairRequest: String = "N/A",
    var AppScheduleDate: String = "N/A"

)
